[package]
name = "fiber_json"
version = "0.1.0"
edition = "2024"

[dependencies]
fiber_string.workspace = true
indexmap.workspace = true
base64.workspace = true
serde_json.workspace = true
serde.workspace = true
